# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gareth Ferguson Blog
email: gareth.f@hotmail.co.uk
description: > # this means to ignore newlines until "baseurl:"
  A blog site aimed at developers
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://garethf89.github.io" # the base hostname & protocol for your site
twitter_username: gazmatron1
github_username:  garethf89

# Build settings
markdown: kramdown
exclude: ["bower_components", "bower.json","Gemfile", "Gemfile.lock", "node_modules", "grunt", "Gruntfile.js", "package.json"]
gems: [bourbon]
